name: Build and Release on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true

      - name: Build for Windows x64
        run: |
          GOOS=windows GOARCH=amd64 go build -v -o rust_updater_windows_amd64.exe ./cmd/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: rust_updater_windows_amd64.exe
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 